### PR TITLE
Upgrade all dependencies & enforce action.type

### LINKED ISSUE #25: when to update to babel6 ?
I use the `redux-actions` && `redux-promise` and `React-Native 0.17` ,but the `RN17` use `babel 6`,and and `redux-actions` && `redux-promise` dependency `flux-standard-action` which use `babel 5`
so ,My Project can not be builded success, so that I have to change the `React Native` to 14
So,Could you update to the `Babel 6 `?

### PR DESCRIPTION
**Pull request by JaKXz**
- _`action.type` must be a string or Symbol_ (the latter may or may not be
dropped, so test support can also be removed easily)
- use npm scripts instead of Makefile
- use Babel 6. Closes #25.
- use `nyc` (disclaimer: I'm a collaborator on `nyc`) for code coverage and coveralls
- test against latest versions of Node LTS
- add [`.editorconfig`](http://editorconfig.org/)
- use `mocha.opts` and mocha-friendlier file structure [+this way `__tests__` are not published in the npm package]
- fixes minimatch dependency warnings [from mocha 2.x and babel 5.x]
- specify package files in `package.json files` to reduce published lib size
- use cross-platform-friendly commands with `cross-env` and `rimraf`
- add `yarn.lock` :tada:

@acdlite @yangmillstheory I got a little carried away (when I noticed `iojs` in `.travis.yml`)... hopefully all of this makes sense - apologies for all of it at once.

### CODE REVIEW

**Comment by JaKXz** [comment]
CI is failing because `npm @2` doesn't like unresolved peer dependencies and `eslint-plugin-airbnb-base` hasn't updated its peerDependencies, yet: https://github.com/airbnb/javascript/pull/1111

**Comment by acdlite** [comment]
@JaKXz Sorry I haven't responded to this yet! Been pretty busy lately. This all looks great.

**Comment by JaKXz** [comment]
@acdlite no worries! life first 👍

**Comment by acdlite** [comment]
Btw I just sent you an email

**Pull request merged**
